// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	entity "recything/features/trash_category/entity"

	mock "github.com/stretchr/testify/mock"

	pagination "recything/utils/pagination"
)

// TrashCategoryServiceInterface is an autogenerated mock type for the TrashCategoryServiceInterface type
type TrashCategoryServiceInterface struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: data
func (_m *TrashCategoryServiceInterface) CreateCategory(data entity.TrashCategoryCore) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.TrashCategoryCore) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCategory provides a mock function with given fields: idTrash
func (_m *TrashCategoryServiceInterface) DeleteCategory(idTrash string) error {
	ret := _m.Called(idTrash)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(idTrash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCategory provides a mock function with given fields: page, limit, search
func (_m *TrashCategoryServiceInterface) GetAllCategory(page string, limit string, search string) ([]entity.TrashCategoryCore, pagination.PageInfo, int, error) {
	ret := _m.Called(page, limit, search)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategory")
	}

	var r0 []entity.TrashCategoryCore
	var r1 pagination.PageInfo
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]entity.TrashCategoryCore, pagination.PageInfo, int, error)); ok {
		return rf(page, limit, search)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []entity.TrashCategoryCore); ok {
		r0 = rf(page, limit, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.TrashCategoryCore)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) pagination.PageInfo); ok {
		r1 = rf(page, limit, search)
	} else {
		r1 = ret.Get(1).(pagination.PageInfo)
	}

	if rf, ok := ret.Get(2).(func(string, string, string) int); ok {
		r2 = rf(page, limit, search)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(string, string, string) error); ok {
		r3 = rf(page, limit, search)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetById provides a mock function with given fields: idTrash
func (_m *TrashCategoryServiceInterface) GetById(idTrash string) (entity.TrashCategoryCore, error) {
	ret := _m.Called(idTrash)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 entity.TrashCategoryCore
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (entity.TrashCategoryCore, error)); ok {
		return rf(idTrash)
	}
	if rf, ok := ret.Get(0).(func(string) entity.TrashCategoryCore); ok {
		r0 = rf(idTrash)
	} else {
		r0 = ret.Get(0).(entity.TrashCategoryCore)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(idTrash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory provides a mock function with given fields: idTrash, data
func (_m *TrashCategoryServiceInterface) UpdateCategory(idTrash string, data entity.TrashCategoryCore) (entity.TrashCategoryCore, error) {
	ret := _m.Called(idTrash, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 entity.TrashCategoryCore
	var r1 error
	if rf, ok := ret.Get(0).(func(string, entity.TrashCategoryCore) (entity.TrashCategoryCore, error)); ok {
		return rf(idTrash, data)
	}
	if rf, ok := ret.Get(0).(func(string, entity.TrashCategoryCore) entity.TrashCategoryCore); ok {
		r0 = rf(idTrash, data)
	} else {
		r0 = ret.Get(0).(entity.TrashCategoryCore)
	}

	if rf, ok := ret.Get(1).(func(string, entity.TrashCategoryCore) error); ok {
		r1 = rf(idTrash, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTrashCategoryServiceInterface creates a new instance of TrashCategoryServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrashCategoryServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrashCategoryServiceInterface {
	mock := &TrashCategoryServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
